export {
  DEFAULT_THEME_PREFERENCE,
  DEFAULT_THEME_PREFERENCES,
  THEME_PREF_KEY,
  applyResolvedTheme,
  loadThemePreferences,
  readSystemTheme,
  resolveEffectiveTheme,
  saveThemePreferences,
  setStoredTheme,
  type ResolvedTheme,
  type ThemePreference,
  type ThemePreferences,
  type ThemePreferencesStorage,
} from './theme-preferences';
export {
  ACCENT_PREF_KEY,
  DEFAULT_ACCENT_HEX,
  loadAccentPreferences,
} from './accent-preferences';
export {
  ThemeProvider,
  useTheme,
  type ThemeProviderProps,
} from './ThemeProvider';
export {
  BACKGROUND_DISPLAY_MODES,
  BACKGROUND_PREFERENCES_KEY,
  BACKGROUND_PREFERENCES_VERSION,
  DEFAULT_BACKGROUND_PREFERENCES,
  MAX_BACKGROUND_IMAGE_DATA_URL_BYTES,
  applyBackgroundPreferences,
  backgroundImageDataUrlSchema,
  backgroundPreferencesSchema,
  clearBackgroundPreferences,
  isSafeBackgroundImageDataUrl,
  loadBackgroundPreferences,
  normalizeBackgroundDisplayMode,
  normalizeBackgroundImageDataUrl,
  normalizeBackgroundImageOpacity,
  normalizeBackgroundPreferences,
  parseBackgroundPreferences,
  saveBackgroundPreferences,
  validateBackgroundPreferences,
  type BackgroundDisplayMode,
  type BackgroundPreferences,
  type BackgroundPreferencesStorage,
} from './background-preferences';
export {
  CUSTOM_THEME_COLOR_TOKENS,
  CUSTOM_THEME_PREF_KEY,
  CUSTOM_THEME_VERSION,
  DEFAULT_CUSTOM_THEME,
  applyCustomTheme,
  clearCustomTheme,
  customThemeOverridesSchema,
  customThemeSchema,
  loadCustomTheme,
  saveCustomTheme,
  type CustomTheme,
  type CustomThemeColorToken,
  type CustomThemeMode,
  type CustomThemeOverrides,
} from './custom-theme';
export {
  resolveEffectiveThemeTokens,
  type EffectiveThemeTokenResult,
} from './theme-composition';
export {
  DEFAULT_THEME_PROFILE,
  THEME_PROFILE_IDS,
  THEME_PROFILE_PREF_KEY,
  THEME_PROFILE_PRESETS,
  THEME_PROFILE_VERSION,
  applyThemeProfile,
  loadThemeProfile,
  parseThemeProfile,
  resolveThemeProfile,
  saveThemeProfile,
  themeProfileOverridesSchema,
  themeProfileSchema,
  type ThemeProfile,
  type ThemeProfileId,
  type ThemeProfileOverrides,
  type ThemeProfilePreset,
  type ThemeProfileTokenMap,
} from './theme-profiles';
